services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: safi_dev
    restart: always
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - MONGO_URI=mongodb://mongo:27017/safi_db
    volumes:
      - .:/app
    depends_on:
      - mongo

  test_runner:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: pytest
    volumes:
      - .:/app
    environment:
      - FLASK_DEBUG=1
      - MONGO_URI=mongodb://mongo:27017/safi_test_db
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: safi_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
